JokesWebApp/Models/ErrorViewModel.cs
namespace JokesWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JokesWebApp/Models/Jokes.cs
namespace JokesWebApp.Models
{
    public class Jokes
    {
        public int Id { get; set; }

        public string Autor { get; set; }
        public string JokePergunta { get; set; }
        public string JokesRespostas { get; set; }

        public Jokes() {
            Id = 0;
            Autor = string.Empty;
            JokePergunta = string.Empty;
            JokesRespostas = string.Empty;
        }
    }
}

JokesWebApp/Controllers/HomeController.cs
using JokesWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace JokesWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JokesWebApp/Controllers/JokesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JokesWebApp.Data;
using JokesWebApp.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace JokesWebApp.Controllers
{
    public class JokesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JokesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Jokes
        public async Task<IActionResult> Index()
        {
              return _context.Jokes != null ? 
                          View(await _context.Jokes.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Jokes'  is null.");
        }

        // GET: ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            //return _context.Jokes != null ?
            //View(await _context.Jokes.ToListAsync()) :
            //Problem("Entity set 'ApplicationDbContext.Jokes'  is null.");
            return View();
        }

        // POST: ShowFormResultados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ShowFormResultados(string SearchFrase)
        {
            return _context.Jokes != null ?
            View("Index", await _context.Jokes.Where( j => j.JokePergunta.Contains(SearchFrase)).ToListAsync()) :
            Problem("Entity set 'ApplicationDbContext.Jokes'  is null.");
 
        }

        // GET: Jokes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Jokes == null)
            {
                return NotFound();
            }

            var jokes = await _context.Jokes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jokes == null)
            {
                return NotFound();
            }

            return View(jokes);
        }

        // GET: Jokes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jokes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,JokePergunta,JokesRespostas,Autor")] Jokes jokes)
        {
            if (ModelState.IsValid)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                jokes.Autor = userId;
                _context.Add(jokes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(jokes);
        }

        // GET: Jokes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Jokes == null)
            {
                return NotFound();
            }

            var jokes = await _context.Jokes.FindAsync(id);
            if (jokes == null)
            {
                return NotFound();
            }
            return View(jokes);
        }

        // POST: Jokes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,JokePergunta,JokesRespostas")] Jokes jokes)
        {
            if (id != jokes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jokes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JokesExists(jokes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jokes);
        }

        // GET: Jokes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Jokes == null)
            {
                return NotFound();
            }

            var jokes = await _context.Jokes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jokes == null)
            {
                return NotFound();
            }

            return View(jokes);
        }

        // POST: Jokes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Jokes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Jokes'  is null.");
            }
            var jokes = await _context.Jokes.FindAsync(id);
            if (jokes != null)
            {
                _context.Jokes.Remove(jokes);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JokesExists(int id)
        {
          return (_context.Jokes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

JokesWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Principal";
}

<div class="text-center">
    <h1 class="display-4">Piadas de Partir o "uobo" a Rir!</h1>
    <p>Diogo Correia Carlos</a></p>
    <div>
        <img src=~/css/uobo.jpg />
    </div>
</div>

JokesWebApp/Views/Jokes/Create.cshtml
@model JokesWebApp.Models.Jokes

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>Jokes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JokePergunta" class="control-label"></label>
                <input asp-for="JokePergunta" class="form-control" />
                <span asp-validation-for="JokePergunta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JokesRespostas" class="control-label"></label>
                <input asp-for="JokesRespostas" class="form-control" />
                <span asp-validation-for="JokesRespostas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">volta pra lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JokesWebApp/Views/Jokes/Delete.cshtml
@model JokesWebApp.Models.Jokes

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>tem acerteza que deseja eliminar isto?</h3>
<div>
    <h4>Jokes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokePergunta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokePergunta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokesRespostas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokesRespostas)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">voltar pra lista</a>
    </form>
</div>

JokesWebApp/Views/Jokes/Details.cshtml
@model JokesWebApp.Models.Jokes

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Jokes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokePergunta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokePergunta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokesRespostas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokesRespostas)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
    <a asp-action="Index">volta pra lista</a>
</div>

JokesWebApp/Views/Jokes/Edit.cshtml
@model JokesWebApp.Models.Jokes

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Jokes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="JokePergunta" class="control-label"></label>
                <input asp-for="JokePergunta" class="form-control" />
                <span asp-validation-for="JokePergunta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JokesRespostas" class="control-label"></label>
                <input asp-for="JokesRespostas" class="form-control" />
                <span asp-validation-for="JokesRespostas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">voltar pra lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JokesWebApp/Views/Jokes/Index.cshtml
@model IEnumerable<JokesWebApp.Models.Jokes>

@{
    ViewData["Title"] = "Index";
}

<h1>Indice</h1>

<p>
    <a asp-action="Create">Criar novo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JokePergunta) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.JokePergunta)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Autor)
                </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

JokesWebApp/Views/Jokes/ShowSearchForm.cshtml
<h4>Procurar Joke</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowFormResultados">

            <div class="form-group">
                <label name="JokePergunta" class="control-label"></label>
                <input name="SearchFrase" class="form-control" />

            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">voltar pra lista</a>
</div>

JokesWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JokesWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JokesWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JokesWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jokes" asp-action="Index">Jokes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jokes" asp-action="ShowSearchForm">Procurar</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - JokesWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>